name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install Composer dependencies
        run: |
          cd inventory-app
          composer install --no-interaction --no-progress
      - name: Prepare database
        run: |
          cd inventory-app
          touch database/database.sqlite
          php artisan migrate
      - name: Run tests
        run: |
          cd inventory-app
          php artisan test
