name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, sqlite3, openssl, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: inventory-app

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: inventory-app

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: inventory-app

      - name: Run Pint (test mode)
        run: ./vendor/bin/pint --test
        working-directory: inventory-app

      - name: Run Pest tests
        run: ./vendor/bin/pest
        working-directory: inventory-app
